application: weavebrowser
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: standalone.html
  upload: standalone.html
  secure: always

- url: /favicon.ico
  static_files: skin/weave.ico
  upload: skin/weave.ico

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /skin
  static_dir: skin

- url: /jsbn
  static_dir: jsbn

- url: /weave
  static_dir: weave

- url: /.*
  script: app.py
  secure: always
